# all positions which would cover this aerodrome top-down if online on their own
AIRPORT_POSITIONS = {
    "CYYZ": {
        "DEL": [],
        "GND": ["CYYZ_GND"],
        "TWR": ["CYYZ_TWR"],
        "APP": ["TOR_AA_APP"],
        "ACC": [],
    },
    "EBAW": {
        "DEL": [],
        "GND": ["EBAW_GND"],
        "TWR": ["EBAW_TWR"],
        "APP": ["EBBR_APP", "EBBR_DEP"],
        "ACC": ["EBBU_E_CTR", "EBBU_W_CTR", "EBBU_LOW_CTR"],
    },
    "EBBR": {
        "DEL": ["EBBR_DEL", "EBBR_P_DEL"],
        "GND": ["EBBR_GND", "EBBR_C_GND", "EBBR_S_GND"],
        "TWR": ["EBBR_TWR", "EBBR_N_TWR"],
        "APP": ["EBBR_APP", "EBBR_F_APP", "EBBR_DEP"],
        "ACC": ["EBBU_E_CTR", "EBBU_W_CTR", "EBBU_LOW_CTR"],
    },
    "EBCI": {
        "DEL": [],
        "GND": ["EBCI_GND"],
        "TWR": ["EBCI_TWR"],
        "APP": ["EBCI_APP", "EBBR_APP", "EBBR_DEP"],
        "ACC": ["EBBU_E_CTR", "EBBU_W_CTR", "EBBU_LOW_CTR"],
    },
    "EBKT": {
        "DEL": [],
        "GND": [],
        "TWR": ["EBKT_I_TWR"],
        "APP": [],
        "ACC": ["EBBU_E_CTR", "EBBU_W_CTR", "EBBU_LOW_CTR"],
    },
    "EBLG": {
        "DEL": [],
        "GND": ["EBLG_GND"],
        "TWR": ["EBLG_TWR"],
        "APP": ["EBLG_APP"],
        "ACC": ["EBBU_E_CTR", "EBBU_W_CTR", "EBBU_LOW_CTR"],
    },
    "EBOS": {
        "DEL": [],
        "GND": ["EBOS_GND"],
        "TWR": ["EBOS_TWR"],
        "APP": ["EBOS_APP"],
        "ACC": ["EBBU_E_CTR", "EBBU_W_CTR", "EBBU_LOW_CTR"],
    },
    "EDDF": {
        "DEL": ["EDDF_DEL"],
        "GND": ["EDDF_C_GND", "EDDF_E_GND", "EDDF_W_GND"],
        "TWR": ["EDDF_C_TWR", "EDDF_W1_TWR"],
        "APP": ["EDDF_H_APP", "EDDF_L_APP", "EDDF_N_APP", "EDDF_S_APP"],
        "ACC": ["EDGG_C_CTR", "EDGG_DKB_CTR", "EDGG_HEF_CTR", "EDGG_RUS_CTR", "EDGG_SH_CTR"],
    },
    "EDDM": {
        "DEL": [],
        "GND": ["EDDM_2_GND"],
        "TWR": ["EDDM_N_TWR"],
        "APP": ["EDDM_NH_APP"],
        "ACC": ["EDMM_ZUG_CTR"],
    },
    "EDDN": {
        "DEL": [],
        "GND": ["EDDN_GND"],
        "TWR": ["EDDN_TWR"],
        "APP": [],
        "ACC": ["EDMM_BBG_CTR"],
    },
    "EDDR": {
        "DEL": [],
        "GND": [],
        "TWR": [],
        "APP": ["EDDR_PFA_APP"],
        "ACC": [],
    },
    "EDFH": {
        "DEL": [],
        "GND": ["EDFH_GND"],
        "TWR": ["EDFH_TWR"],
        "APP": ["EDDR_PFA_APP", "EDFH_EIF_APP"],
        "ACC": ["EDGG_C_CTR"],
    },
    "EFHK": {
        "DEL": ["EFHK_DEL"],
        "GND": ["EFHK_GND"],
        "TWR": ["EFHK_E_TWR"],
        "APP": ["EFHK_E_APP", "EFHK_R_APP", "EFHK_W_APP"],
        "ACC": ["EFIN_D_CTR"],
    },
    "EGKK": {
        "DEL": ["EGKK_DEL"],
        "GND": ["EGKK_N_GND"],
        "TWR": ["EGKK_TWR"],
        "APP": ["EGKK_APP"],
        "ACC": ["LON_S_CTR", "LTC_S_CTR"],
    },
    "EGLL": {
        "DEL": [],
        "GND": ["EGLL_2_GND"],
        "TWR": ["EGLL_S_TWR"],
        "APP": [],
        "ACC": ["LON_S_CTR", "LTC_S_CTR"],
    },
    "EGSS": {
        "DEL": [],
        "GND": [],
        "TWR": ["EGSS_TWR"],
        "APP": ["ESSEX_APP"],
        "ACC": [],
    },
    "EHAM": {
        "DEL": [],
        "GND": ["EHAM_N_GND"],
        "TWR": [],
        "APP": ["EHAM_W_APP"],
        "ACC": [],
    },
    "ELLX": {
        "DEL": ["ELLX_DEL"],
        "GND": [],
        "TWR": ["ELLX_TWR"],
        "APP": ["ELLX_APP", "ELLX_F_APP"],
        "ACC": ["EBBU_E_CTR", "EBBU_W_CTR", "EBBU_L_CTR", "EBBU_LOW_CTR"],
    },
    "ENGM": {
        "DEL": [],
        "GND": [],
        "TWR": ["ENGM_W_TWR"],
        "APP": ["ENGM_W_APP"],
        "ACC": [],
    },
    "EVRA": {
        "DEL": [],
        "GND": ["EVRA_GND"],
        "TWR": ["EVRA_TWR"],
        "APP": ["EVRA_APP"],
        "ACC": ["EVRR_CTR"],
    },
    "EYVI": {
        "DEL": [],
        "GND": [],
        "TWR": ["EYVI_TWR"],
        "APP": ["EYVI_APP"],
        "ACC": ["EYVL_CTR"],
    },
    "HECA": {
        "DEL": [],
        "GND": ["HECA_2_GND"],
        "TWR": ["HECA_TWR"],
        "APP": ["HECA_APP"],
        "ACC": ["HECC_CTR"],
    },
    "KBOS": {
        "DEL": ["BOS_DEL"],
        "GND": ["BOS_GND"],
        "TWR": ["BOS_TWR"],
        "APP": ["BOS_APP"],
        "ACC": ["BOS_1_CTR"],
    },
    "KORD": {
        "DEL": [],
        "GND": ["ORD_I_GND"],
        "TWR": ["ORD_S_TWR", "ORD_S1_TWR"],
        "APP": ["CHI_Z_APP"],
        "ACC": ["CHI_35_CTR"],
    },
    "LBSF": {
        "DEL": ["LBSF_DEL"],
        "GND": [],
        "TWR": ["LBSF_TWR"],
        "APP": ["LBSF_APP"],
        "ACC": ["LBSR_CTR"],
    },
    "LGAV": {
        "DEL": ["LGAV_DEL"],
        "GND": [],
        "TWR": ["LGAV_E_TWR", "LGAV_W_TWR"],
        "APP": ["LGAV_W_APP"],
        "ACC": ["LGGG_CTR"],
    },
    "LIEO": {
        "DEL": [],
        "GND": ["LIEO_GND"],
        "TWR": [],
        "APP": ["LIEO_EW0_APP"],
        "ACC": ["LIRR_SU1_CTR"],
    },
    "LPPR": {
        "DEL": ["LPPR_DEL"],
        "GND": ["LPPR_GND"],
        "TWR": ["LPPR_TWR"],
        "APP": ["LPPR_APP"],
        "ACC": ["LPPC_CTR", "LPPC_E_CTR"],
    },
}
