# all positions which would cover this aerodrome top-down if online on their own
# all positions are MANUALLY validated, so holes are there! if you are knowledgeable in the control over any aerodrome(s), please submit positions to be added!


AIRPORT_POSITIONS = {
    "CYYZ": {
        "DEL": [],
        "GND": ["CYYZ_GND"],
        "TWR": ["CYYZ_TWR"],
        "APP": ["TOR_AA_APP"],
        "ACC": [],
    },
    "EBAW": {
        "DEL": [],
        "GND": ["EBAW_GND"],
        "TWR": ["EBAW_TWR"],
        "APP": ["EBBR_APP", "EBBR_DEP"],
        "ACC": ["EBBU_E_CTR", "EBBU_W_CTR", "EBBU_LOW_CTR"],
    },
    "EBBR": {
        "DEL": ["EBBR_DEL", "EBBR_P_DEL"],
        "GND": ["EBBR_GND", "EBBR_C_GND", "EBBR_S_GND"],
        "TWR": ["EBBR_TWR", "EBBR_N_TWR"],
        "APP": ["EBBR_APP", "EBBR_F_APP", "EBBR_DEP"],
        "ACC": ["EBBU_E_CTR", "EBBU_W_CTR", "EBBU_LOW_CTR"],
    },
    "EBCI": {
        "DEL": [],
        "GND": ["EBCI_GND"],
        "TWR": ["EBCI_TWR"],
        "APP": ["EBCI_APP", "EBBR_APP", "EBBR_DEP"],
        "ACC": ["EBBU_E_CTR", "EBBU_W_CTR", "EBBU_LOW_CTR"],
    },
    "EBKT": {
        "DEL": [],
        "GND": [],
        "TWR": ["EBKT_I_TWR"],
        "APP": [],
        "ACC": ["EBBU_E_CTR", "EBBU_W_CTR", "EBBU_LOW_CTR"],
    },
    "EBLG": {
        "DEL": [],
        "GND": ["EBLG_GND"],
        "TWR": ["EBLG_TWR"],
        "APP": ["EBLG_APP"],
        "ACC": ["EBBU_E_CTR", "EBBU_W_CTR", "EBBU_LOW_CTR"],
    },
    "EBOS": {
        "DEL": [],
        "GND": ["EBOS_GND"],
        "TWR": ["EBOS_TWR"],
        "APP": ["EBOS_APP"],
        "ACC": ["EBBU_E_CTR", "EBBU_W_CTR", "EBBU_LOW_CTR"],
    },
    "EDDB": {
        "DEL": [],
        "GND": [],
        "TWR": [],
        "APP": ["EDDB_S_APP"],
        "ACC": ["EDWW_CTR", "EDWW_MAR_CTR"],
    },
    "EDDF": {
        "DEL": ["EDDF_DEL"],
        "GND": ["EDDF_C_GND", "EDDF_E_GND", "EDDF_W_GND"],
        "TWR": ["EDDF_C_TWR", "EDDF_W1_TWR"],
        "APP": ["EDDF_H_APP", "EDDF_L_APP", "EDDF_N_APP", "EDDF_S_APP"],
        "ACC": ["EDGG_C_CTR", "EDGG_DKB_CTR", "EDGG_HEF_CTR", "EDGG_RUS_CTR", "EDGG_SH_CTR", "EDGG_BAH_CTR"],
    },
    "EDDH": {
        "DEL": ["EDDH_DEL"],
        "GND": ["EDDH_E_GND", "EDDH_W_GND"],
        "TWR": ["EDDH_TWR"],
        "APP": ["EDDH_APP", "EDDH_A_APP"],
        "ACC": ["EDWW_CTR", "EDWW_ALR_CTR"],
    },
    "EDDK": {
        "DEL": ["EDDK_DEL"],
        "GND": ["EDDK_GND"],
        "TWR": ["EDDK_TWR"],
        "APP": ["EDDK_NOR_APP", "EDGG_KL_APP"],
        "ACC": ["EDGG_NH_CTR"],
    },
    "EDDL": {
        "DEL": ["EDDL_DEL"],
        "GND": ["EDDL_E_GND", "EDDL_W_GND"],
        "TWR": ["EDDL_TWR"],
        "APP": ["EDDL_APP", "EDDL_F_APP", "EDGG_KL_APP"],
        "ACC": ["EDGG_NH_CTR"],
    },
    "EDDM": {
        "DEL": ["EDDM_DEL"],
        "GND": ["EDDM_1_GND", "EDDM_2_GND"],
        "TWR": ["EDDM_N_TWR"],
        "APP": ["EDDM_NH_APP"],
        "ACC": ["EDMM_ZUG_CTR"],
    },
    "EDDN": {
        "DEL": [],
        "GND": ["EDDN_GND"],
        "TWR": ["EDDN_TWR"],
        "APP": ["EDDN_D_APP", "EDDN_FRK_APP"],
        "ACC": ["EDMM_BBG_CTR"],
    },
    "EDDP": {
        "DEL": ["EDDP_DEL"],
        "GND": ["EDDP_GND"],
        "TWR": ["EDDP_N_TWR", "EDDP_S_TWR"],
        "APP": ["EDDP_TRN_APP", "EDDP_TRS_APP", "EDDP_SD_APP"],
        "ACC": ["EDMM_BBG_CTR", "EDMM_GER_CTR", "EDMM_MEI_CTR"],
    },
    "EDDR": {
        "DEL": [],
        "GND": [],
        "TWR": ["EDDR_TWR"],
        "APP": ["EDDR_PFA_APP"],
        "ACC": [],
    },
    "EDDS": {
        "DEL": ["EDDS_DEL"],
        "GND": ["EDDS_GND"],
        "TWR": ["EDDS_TWR"],
        "APP": [],
        "ACC": ["EDGG_BAH_CTR"],
    },
    "EDDV": {
        "DEL": ["EDDV_DEL"],
        "GND": [],
        "TWR": [],
        "APP": ["EDDV_APP"],
        "ACC": ["EDWW_EMS_CTR"],
    },
    "EDFH": {
        "DEL": [],
        "GND": ["EDFH_GND"],
        "TWR": ["EDFH_TWR"],
        "APP": ["EDDR_PFA_APP", "EDFH_EIF_APP"],
        "ACC": ["EDGG_C_CTR", "EDGG_CS_CTR"],
    },
    "EDJA": {
        "DEL": [],
        "GND": [],
        "TWR": ["EDJA_TWR"],
        "APP": [],
        "ACC": ["EDMM_ZUG_CTR"],
    },
    "EETN": {
        "DEL": [],
        "GND": [],
        "TWR": ["EETN_TWR"],
        "APP": ["EETN_APP", "EETN_D_APP"],
        "ACC": ["EETT_W_CTR"],
    },
    "EFHK": {
        "DEL": ["EFHK_DEL"],
        "GND": ["EFHK_GND"],
        "TWR": ["EFHK_E_TWR"],
        "APP": ["EFHK_E_APP", "EFHK_R_APP", "EFHK_W_APP"],
        "ACC": ["EFIN_D_CTR"],
    },
    "EGAA": {
        "DEL": [],
        "GND": ["EGAA_GND"],
        "TWR": [],
        "APP": ["EGAA_APP"],
        "ACC": [],
    },
    "EGBB": {
        "DEL": ["EGBB_DEL"],
        "GND": ["EGBB_GND"],
        "TWR": ["EGBB_TWR"],
        "APP": ["EGBB_APP"],
        "ACC": ["LON_CTR", "LON_C_CTR", "LON_M_CTR"],
    },
    "EGCC": {
        "DEL": ["EGCC_DEL",],
        "GND": ["EGCC_GND"],
        "TWR": ["EGCC_N_TWR"],
        "APP": ["EGCC_S_APP"],
        "ACC": ["LON_CTR", "LON_N_CTR", "LON_NW_CTR", "MAN_CTR", "MAN_WI_CTR"],
    },
    "EGGD": {
        "DEL": [],
        "GND": ["EGGD_GND"],
        "TWR": ["EGGD_TWR"],
        "APP": ["EGGD_APP"],
        "ACC": ["LON_CTR", "LON_W_CTR"],
    },
    "EGGP": {
        "DEL": [],
        "GND": ["EGGP_GND"],
        "TWR": ["EGGP_TWR"],
        "APP": ["EGGP_APP"],
        "ACC": ["LON_CTR", "LON_N_CTR", "LON_NW_CTR"],
    },
    "EGGW": {
        "DEL": ["EGGW_DEL"],
        "GND": ["EGGW_GND"],
        "TWR": ["EGGW_TWR"],
        "APP": ["EGGW_APP", "ESSEX_APP"],
        "ACC": ["LON_CTR", "LON_C_CTR", "LON_M_CTR"],
    },
    "EGKK": {
        "DEL": ["EGKK_DEL"],
        "GND": ["EGKK_N_GND"],
        "TWR": ["EGKK_TWR"],
        "APP": ["EGKK_APP"],
        "ACC": ["LON_CTR", "LON_S_CTR", "LTC_S_CTR", "LTC_SW_CTR"],
    },
    "EGLL": {
        "DEL": [],
        "GND": ["EGLL_2_GND"],
        "TWR": ["EGLL_S_TWR"],
        "APP": ["EGLL_N_APP"],
        "ACC": ["LON_CTR", "LON_S_CTR", "LTC_S_CTR", "LTC_SW_CTR"],
    },
    "EGNX": {
        "DEL": [],
        "GND": ["EGNX_GND"],
        "TWR": ["EGNX_TWR"],
        "APP": ["EGNX_APP"],
        "ACC": ["LON_CTR", "LON_C_CTR", "LON_M_CTR"],
    },
    "EGSS": {
        "DEL": [],
        "GND": [],
        "TWR": ["EGSS_TWR"],
        "APP": ["EGSS_APP", "ESSEX_APP"],
        "ACC": ["LON_CTR", "LON_C_CTR"],
    },
    "EHAM": {
        "DEL": ["EHAM_DEL"],
        "GND": ["EHAM_N_GND", "EHAM_S_GND"],
        "TWR": ["EHAM_M_TWR"],
        "APP": ["EHAM_W_APP"],
        "ACC": ["EHAA_LOW_CTR"],
    },
    "EHEH": {
        "DEL": [],
        "GND": ["EHEH_GND"],
        "TWR": ["EHEH_TWR"],
        "APP": ["EHEH_APP"],
        "ACC": ["EHAA_LOW_CTR"],
    },
    "EHRD": {
        "DEL": ["EHRD_DEL"],
        "GND": [],
        "TWR": ["EHRD_TWR"],
        "APP": ["EHRD_APP", "EHAM_W_APP"],
        "ACC": ["EHAA_LOW_CTR"],
    },
    "EICK": {
        "DEL": [],
        "GND": ["EICK_GND"],
        "TWR": ["EICK_TWR"],
        "APP": ["EICK_APP"],
        "ACC": ["EISN_CTR"],
    },
    "EIDW": {
        "DEL": ["EIDW_DEL"],
        "GND": ["EIDW_N_GND", "EIDW_S_GND"],
        "TWR": ["EIDW_N_TWR", "EIDW_S_TWR"],
        "APP": ["EIDW_APP", "EIDW_F_APP"],
        "ACC": ["EIDW_LN_CTR", "EIDW_UN_CTR", "EIDW_LS_CTR", "EIDW_US_CTR", "EISN_CTR"],
    },
    "EKCH": {
        "DEL": [],
        "GND": ["EKCH_A_GND", "EKCH_C_GND"],
        "TWR": ["EKCH_A_TWR", "EKCH_D_TWR"],
        "APP": ["EKCH_P_APP", "EKCH_F_APP", "EKCH_O_APP", "EKCH_W_APP", "EKCH_K_DEP"],
        "ACC": ["EKDK_CTR", "EKDK_UC_CTR", "EKDK_E_CTR", "EKDK_B_CTR"],
    },
    "ELLX": {
        "DEL": ["ELLX_DEL"],
        "GND": [],
        "TWR": ["ELLX_TWR"],
        "APP": ["ELLX_APP", "ELLX_F_APP"],
        "ACC": ["EBBU_E_CTR", "EBBU_W_CTR", "EBBU_L_CTR", "EBBU_LOW_CTR"],
    },
    "ENBR": {
        "DEL": ["ENBR_DEL"],
        "GND": ["ENBR_GND",],
        "TWR": ["ENBR_TWR"],
        "APP": ["ENBR_W_APP"],
        "ACC": ["ENOR_S_CTR"],
    },
    "ENGM": {
        "DEL": [],
        "GND": [],
        "TWR": ["ENGM_W_TWR"],
        "APP": ["ENGM_W_APP"],
        "ACC": ["ENOR_S_CTR", "ENOS_CTR"],
    },
    "ENZV": {
        "DEL": [],
        "GND": ["ENZV_GND"],
        "TWR": ["ENZV_TWR"],
        "APP": ["ENZV_APP"],
        "ACC": ["ENOR_S_CTR"],
    },
    "ESSA": {
        "DEL": ["ESSA_DEL"],
        "GND": [],
        "TWR": [],
        "APP": ["ESSA_E_APP"],
        "ACC": [],
    },
    "EVRA": {
        "DEL": [],
        "GND": ["EVRA_GND"],
        "TWR": ["EVRA_TWR"],
        "APP": ["EVRA_APP"],
        "ACC": ["EVRR_CTR"],
    },
    "EYKA": {
        "DEL": [],
        "GND": [],
        "TWR": ["EYKA_TWR"],
        "APP": [],
        "ACC": ["EYVL_CTR"],
    },
    "EYPA": {
        "DEL": [],
        "GND": [],
        "TWR": ["EYPA_TWR"],
        "APP": [],
        "ACC": ["EYVL_CTR"],
    },
    "EYVI": {
        "DEL": [],
        "GND": [],
        "TWR": ["EYVI_TWR"],
        "APP": ["EYVI_APP"],
        "ACC": ["EYVL_CTR"],
    },
    "FZAA": {
        "DEL": [],
        "GND": [],
        "TWR": ["FZAA_TWR"],
        "APP": ["FZAA_APP"],
        "ACC": [],
    },
    "HECA": {
        "DEL": ["HECA_DEL"],
        "GND": ["HECA_2_GND"],
        "TWR": ["HECA_TWR"],
        "APP": ["HECA_APP"],
        "ACC": ["HECC_CTR", "HECC_1_CTR"],
    },
    "KBOS": {
        "DEL": ["BOS_DEL"],
        "GND": ["BOS_GND"],
        "TWR": ["BOS_TWR"],
        "APP": ["BOS_APP"],
        "ACC": ["BOS_1_CTR"],
    },
    "KEVV": {
        "DEL": ["EVV_DEL"],
        "GND": ["EVV_GND"],
        "TWR": ["EVV_TWR"],
        "APP": ["EVV_W_APP"],
        "ACC": [],
    },
    "KEWR": {
        "DEL": ["EWR_DEL"],
        "GND": ["EWR_GND"],
        "TWR": ["EWR_TWR"],
        "APP": ["EWR_DEP", "EWR_A_APP", "EWR_P_APP", "EWR_H_APP", "NY_APP", "NY_T_APP", "NY_L_APP"],
        "ACC": ["NY_CTR"],
    },
    "KFLL": {
        "DEL": [],
        "GND": ["FLL_N_GND"],
        "TWR": ["FLL_N_TWR"],
        "APP": ["MIA_D_DEP"],
        "ACC": ["MIA_06_CTR"],
    },
    "KLGA": {
        "DEL": ["LGA_DEL"],
        "GND": ["LGA_GND"],
        "TWR": ["LGA_TWR"],
        "APP": ["NY_APP", "NY_T_APP", "NY_L_APP"],
        "ACC": ["NY_CTR"],
    },
    "KMEM": {
        "DEL": [],
        "GND": ["MEM_21_GND"],
        "TWR": ["MEM_2_TWR"],
        "APP": ["MEM_E_APP"],
        "ACC": ["MEM_22_CTR"],
    },
    "KORD": {
        "DEL": [],
        "GND": ["ORD_I_GND"],
        "TWR": ["ORD_S_TWR", "ORD_S1_TWR"],
        "APP": ["CHI_Z_APP"],
        "ACC": ["CHI_35_CTR"],
    },
    "KTEB": {
        "DEL": ["TEB_DEL"],
        "GND": ["TEB_GND"],
        "TWR": ["TEB_TWR"],
        "APP": ["EWR_DEP", "EWR_A_APP", "EWR_P_APP", "EWR_H_APP", "NY_APP", "NY_T_APP", "NY_L_APP"],
        "ACC": ["NY_CTR"],
    },
    "LBSF": {
        "DEL": ["LBSF_DEL"],
        "GND": [],
        "TWR": ["LBSF_TWR"],
        "APP": ["LBSF_APP"],
        "ACC": ["LBSR_CTR"],
    },
    "LCLK": {
        "DEL": ["LCLK_DEL"],
        "GND": ["LCLK_GND"],
        "TWR": ["LCLK_TWR"],
        "APP": ["LCLK_APP"],
        "ACC": ["LCCC_CTR"],
    },
    "LCPH": {
        "DEL": [],
        "GND": ["LCPH_GND"],
        "TWR": ["LCPH_TWR"],
        "APP": ["LCPH_APP"],
        "ACC": ["LCCC_CTR"],
    },
    "LCRA": {
        "DEL": [],
        "GND": ["LCRA_GND"],
        "TWR": ["LCRA_TWR"],
        "APP": ["LCRA_APP"],
        "ACC": ["LCCC_CTR"],
    },
    "LDSP": {
        "DEL": [],
        "GND": [],
        "TWR": ["LDSP_TWR"],
        "APP": ["LDSP_APP"],
        "ACC": ["ADR_CTR", "ADR_W_CTR", "LDZO_CTR"],
    },
    "LEMD": {
        "DEL": ["LEMD_DEL"],
        "GND": ["LEMD_GND"],
        "TWR": ["LEMD_TWR"],
        "APP": ["LEMD_EN_APP"],
        "ACC": ["LECM_CTR"],
    },
    "LEPA": {
        "DEL": ["LEPA_DEL"],
        "GND": ["LEPA_GND"],
        "TWR": ["LEPA_TWR"],
        "APP": ["LEPA_APP"],
        "ACC": ["LECB_CTR", "LECB_RE_CTR"],
    },
    "LFPG": {
        "DEL": ["LFPG_DEL"],
        "GND": ["LFPG_N_GND"],
        "TWR": [],
        "APP": ["LFPG_N_APP"],
        "ACC": [],
    },
    "LFPO": {
        "DEL": [],
        "GND": ["LFPO_GND"],
        "TWR": [],
        "APP": ["LFPO_APP", "LFPG_N_APP"],
        "ACC": [],
    },
    "LGAV": {
        "DEL": ["LGAV_DEL"],
        "GND": ["LGAV_N_GND"],
        "TWR": ["LGAV_E_TWR", "LGAV_W_TWR"],
        "APP": ["LGAV_W_APP", "LGAV_DEP"],
        "ACC": ["LGGG_CTR", "LGGG_KRK_CTR", "LGMD_W_CTR"],
    },
    "LGKR": {
        "DEL": [],
        "GND": ["LGKR_GND"],
        "TWR": ["LGKR_TWR"],
        "APP": ["LGKR_APP"],
        "ACC": ["LGGG_CTR", "LGGG_KRK_CTR"],
    },
    "LHBP": {
        "DEL": ["LHBP_DEL"],
        "GND": ["LHBP_GND"],
        "TWR": ["LHBP_TWR"],
        "APP": ["LHBP_APP"],
        "ACC": [],
    },
    "LICC": {
        "DEL": [],
        "GND": ["LICC_GND"],
        "TWR": ["LICC_TWR"],
        "APP": ["LICC_APP"],
        "ACC": ["LIRR_SU1_CTR", "LIRR_ES1_CTR"],
    },
    "LICJ": {
        "DEL": [],
        "GND": ["LICJ_GND"],
        "TWR": ["LICJ_TWR"],
        "APP": ["LICJ_APP"],
        "ACC": ["LIRR_SU1_CTR"],
    },
    "LICT": {
        "DEL": [],
        "GND": [],
        "TWR": ["LICT_TWR"],
        "APP": ["LICT_APP"],
        "ACC": ["LIRR_SU1_CTR"],
    },
    "LIEE": {
        "DEL": [],
        "GND": ["LIEE_GND"],
        "TWR": ["LIEE_TWR"],
        "APP": ["LIEE_APP"],
        "ACC": ["LIRR_SU1_CTR", "LIRR_EW1_CTR", "LIRR_EW2_CTR"],
    },
    "LIEO": {
        "DEL": [],
        "GND": ["LIEO_GND"],
        "TWR": ["LIEO_TWR"],
        "APP": ["LIEO_EW0_APP"],
        "ACC": ["LIRR_EW1_CTR", "LIRR_EW2_CTR", "LIRR_SU1_CTR"],
    },
    "LIRF": {
        "DEL": ["LIRF_DEL", "LIRF_P_DEL"],
        "GND": ["LIRF_E_GND", "LIRF_W_GND"],
        "TWR": ["LIRF_TWR", "LIRF_E_TWR"],
        "APP": ["LIRR_PN1_DEP", "LIRR_TW1_APP", "LIRR_AEM_APP"],
        "ACC": ["LIRR_TS1_CTR", "LIRR_NE1_CTR"],
    },
    "LIRN": {
        "DEL": [],
        "GND": ["LIRN_GND"],
        "TWR": ["LIRN_TWR"],
        "APP": ["LIRN_US1_APP"],
        "ACC": ["LIRR_NE1_CTR"],
    },
    "LIRQ": {
        "DEL": [],
        "GND": [],
        "TWR": ["LIRQ_TWR"],
        "APP": ["LIRQ_NN0_APP"],
        "ACC": ["LIRR_NE1_CTR"],
    },
    "LJLJ": {
        "DEL": [],
        "GND": ["LJLJ_GND"],
        "TWR": ["LJLJ_TWR"],
        "APP": ["LJLJ_APP"],
        "ACC": ["LJLA_CTR", "ADR_CTR", "ADR_W_CTR"],
    },
    "LKKV": {
        "DEL": [],
        "GND": [],
        "TWR": ["LKKV_TWR"],
        "APP": [],
        "ACC": ["LKAA_CTR"],
    },
    "LKPR": {
        "DEL": ["LKPR_DEL"],
        "GND": ["LKPR_GND"],
        "TWR": ["LKPR_TWR"],
        "APP": ["LKPR_APP"],
        "ACC": ["LKAA_CTR"],
    },
    "LKPR": {
        "DEL": [],
        "GND": ["LKTB_GND"],
        "TWR": [],
        "APP": [],
        "ACC": ["LKAA_CTR"],
    },
    "LOWI": {
        "DEL": [],
        "GND": [],
        "TWR": ["LOWI_TWR"],
        "APP": ["LOWI_APP"],
        "ACC": ["LOVV_CTR", "LOVV_B_CTR"],
    },
    "LOWW": {
        "DEL": ["LOWW_DEL"],
        "GND": ["LOWW_GND"],
        "TWR": ["LOWW_TWR"],
        "APP": ["LOWW_APP", "LOWW_F_APP"],
        "ACC": ["LOVV_CTR", "LOVV_C_CTR", "LOVV_N_CTR"],
    },
    "LPPR": {
        "DEL": ["LPPR_DEL"],
        "GND": ["LPPR_GND"],
        "TWR": ["LPPR_TWR"],
        "APP": ["LPPR_APP"],
        "ACC": ["LPPC_CTR", "LPPC_E_CTR"],
    },
    "LPPT": {
        "DEL": ["LPPT_DEL"],
        "GND": ["LPPT_GND"],
        "TWR": ["LPPT_TWR"],
        "APP": ["LPPT_APP"],
        "ACC": ["LPPC_CTR"],
    },
    "LROP": {
        "DEL": [],
        "GND": ["LROP_GND"],
        "TWR": ["LROP_TWR"],
        "APP": ["LROP_APP"],
        "ACC": ["LRBB_CTR"],
    },
    "LSGG": {
        "DEL": [],
        "GND": ["LSGG_GND", "LSGG_A_GND"],
        "TWR": ["LSGG_TWR"],
        "APP": ["LSGG_APP"],
        "ACC": ["LSAG_CTR"],
    },
    "LSZH": {
        "DEL": ["LSZH_DEL"],
        "GND": [],
        "TWR": ["LSZH_TWR"],
        "APP": [],
        "ACC": ["LSAZ_CTR"],
    },
    "LTBS": {
        "DEL": [],
        "GND": ["LTBS_GND"],
        "TWR": [],
        "APP": ["LTBS_APP", "LTBS_S_APP"],
        "ACC": ["ANK_WS_CTR"]
    },
    "LTFE": {
        "DEL": [],
        "GND": ["LTFE_GND"],
        "TWR": ["LTFE_TWR"],
        "APP": ["LTFE_APP"],
        "ACC": ["ANK_WS_CTR"]
    },
    "LUKK": {
        "DEL": [],
        "GND": ["LUKK_GND"],
        "TWR": ["LUKK_TWR"],
        "APP": ["LUKK_APP"],
        "ACC": ["LUUU_CTR", "LRBB_CTR"],
    },
    "LYBE": {
        "DEL": ["LYBE_DEL"],
        "GND": ["LYBE_GND"],
        "TWR": ["LYBE_TWR"],
        "APP": ["LYBE_APP"],
        "ACC": ["ADR_CTR", "ADR_E_CTR", "LYBA_CTR"],
    },
    "OBBI": {
        "DEL": ["OBBI_DEL"],
        "GND": ["OBBI_GND"],
        "TWR": ["OBBI_TWR"],
        "APP": ["OBBI_APP", "OBBI_F_APP"],
        "ACC": ["OBBB_1_CTR"],
    },
    "OEJN": {
        "DEL": ["OEJN_DEL"],
        "GND": ["OEJN_W_GND"],
        "TWR": ["OEJN_W_TWR"],
        "APP": ["OEJN_APP"],
        "ACC": ["OEJD_1_CTR"],
    },
    "OJAI": {
        "DEL": [],
        "GND": ["OJAI_GND"],
        "TWR": ["OJAI_TWR"],
        "APP": ["OJAI_APP"],
        "ACC": ["OJAC_CTR"],
    },
    "OKKK": {
        "DEL": ["OKKK_DEL"],
        "GND": ["OKKK_1_GND"],
        "TWR": ["OKKK_TWR"],
        "APP": ["OKKK_APP"],
        "ACC": ["OKAC_CTR"],
    },
    "OMAA": {
        "DEL": ["OMAA_DEL"],
        "GND": ["OMAA_1_GND", "OMAA_2_GND"],
        "TWR": ["OMAA_1_TWR"],
        "APP": ["OMAA_1_APP", "OMAA_2_APP"],
        "ACC": ["OMAE_1_CTR"],
    },
    "OMDB": {
        "DEL": ["OMDB_DEL", "OMDB_P_DEL"],
        "GND": ["OMDB_1_GND", "OMDB_2_GND", "OMDB_P_GND"],
        "TWR": ["OMDB_1_TWR"],
        "APP": ["OMDB_APP"],
        "ACC": ["OMAE_1_CTR"],
    },
    "OPKC": {
        "DEL": [],
        "GND": ["OPKC_GND"],
        "TWR": ["OPKC_TWR"],
        "APP": [],
        "ACC": ["OPKR_CTR"],
    },
    "VCBI": {
        "DEL": ["VCBI_DEL"],
        "GND": ["VCBI_GND"],
        "TWR": ["VCBI_TWR"],
        "APP": ["VCBI_APP"],
        "ACC": ["VCCF_CTR"],
    },
    "VGHS": {
        "DEL": [],
        "GND": [],
        "TWR": ["VGHS_TWR"],
        "APP": ["VGHS_APP"],
        "ACC": ["VGFR_CTR"],
    },
    "VHHH": {
        "DEL": ["VHHH_DEL"],
        "GND": ["VHHH_1_GND"],
        "TWR": ["VHHH_N_TWR", "VHHH_S_TWR"],
        "APP": ["VHHH_APP", "VHHH_F_APP", "VHHH_W_APP"],
        "ACC": ["HKG_S_CTR", "HKG_W_CTR"],
    },
    "VOBL": {
        "DEL": ["VOBL_DEL"],
        "GND": ["VOBL_GND", "VOBL_1_GND"],
        "TWR": ["VOBL_TWR"],
        "APP": ["VOBL_APP"],
        "ACC": ["VOMF_UAC_CTR"],
    },
    "VVTS": {
        "DEL": [],
        "GND": [],
        "TWR": ["VVTS_TWR"],
        "APP": ["VVTS_APP", "VVTS_F_APP"],
        "ACC": ["VCL_CTR"],
    },
    "ZSAM": {
        "DEL": [],
        "GND": [],
        "TWR": ["ZSAM_TWR"],
        "APP": ["ZSAM_APP"],
        "ACC": ["ZSAM_CTR"],
    },
    "ZSPD": {
        "DEL": ["ZSPD_DEL"],
        "GND": ["ZSPD_A_GND", "ZSPD_AS_GND"],
        "TWR": ["ZSPD_TWR"],
        "APP": ["ZSSS_APP", "ZSSS_PF_APP", "ZSSS_W_APP"],
        "ACC": ["ZSSS_CTR"],
    },
}
